/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrganizationIdRouteRouteImport } from './routes/$organizationId/route'
import { Route as OrganizationIdIndexRouteImport } from './routes/$organizationId/index'
import { Route as OrganizationIdLeaderboardRouteImport } from './routes/$organizationId/leaderboard'
import { Route as OrganizationIdPeopleRouteImport } from './routes/$organizationId/people'
import { Route as OrganizationIdMatchesIndexRouteImport } from './routes/$organizationId/matches/index'
import { Route as OrganizationIdMatchesMatchIdRouteImport } from './routes/$organizationId/matches/$matchId'
import { Route as OrganizationIdMatchesNewRouteImport } from './routes/$organizationId/matches/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationIdRouteRoute = OrganizationIdRouteRouteImport.update({
  id: '/$organizationId',
  path: '/$organizationId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationIdIndexRoute = OrganizationIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrganizationIdRouteRoute,
} as any)
const OrganizationIdLeaderboardRoute =
  OrganizationIdLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => OrganizationIdRouteRoute,
  } as any)
const OrganizationIdPeopleRoute = OrganizationIdPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => OrganizationIdRouteRoute,
} as any)
const OrganizationIdMatchesIndexRoute =
  OrganizationIdMatchesIndexRouteImport.update({
    id: '/matches/',
    path: '/matches/',
    getParentRoute: () => OrganizationIdRouteRoute,
  } as any)
const OrganizationIdMatchesMatchIdRoute =
  OrganizationIdMatchesMatchIdRouteImport.update({
    id: '/matches/$matchId',
    path: '/matches/$matchId',
    getParentRoute: () => OrganizationIdRouteRoute,
  } as any)
const OrganizationIdMatchesNewRoute =
  OrganizationIdMatchesNewRouteImport.update({
    id: '/matches/new',
    path: '/matches/new',
    getParentRoute: () => OrganizationIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$organizationId': typeof OrganizationIdRouteRouteWithChildren
  '/$organizationId/leaderboard': typeof OrganizationIdLeaderboardRoute
  '/$organizationId/people': typeof OrganizationIdPeopleRoute
  '/$organizationId/': typeof OrganizationIdIndexRoute
  '/$organizationId/matches/$matchId': typeof OrganizationIdMatchesMatchIdRoute
  '/$organizationId/matches/new': typeof OrganizationIdMatchesNewRoute
  '/$organizationId/matches/': typeof OrganizationIdMatchesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$organizationId/leaderboard': typeof OrganizationIdLeaderboardRoute
  '/$organizationId/people': typeof OrganizationIdPeopleRoute
  '/$organizationId': typeof OrganizationIdIndexRoute
  '/$organizationId/matches/$matchId': typeof OrganizationIdMatchesMatchIdRoute
  '/$organizationId/matches/new': typeof OrganizationIdMatchesNewRoute
  '/$organizationId/matches': typeof OrganizationIdMatchesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$organizationId': typeof OrganizationIdRouteRouteWithChildren
  '/$organizationId/leaderboard': typeof OrganizationIdLeaderboardRoute
  '/$organizationId/people': typeof OrganizationIdPeopleRoute
  '/$organizationId/': typeof OrganizationIdIndexRoute
  '/$organizationId/matches/$matchId': typeof OrganizationIdMatchesMatchIdRoute
  '/$organizationId/matches/new': typeof OrganizationIdMatchesNewRoute
  '/$organizationId/matches/': typeof OrganizationIdMatchesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$organizationId'
    | '/$organizationId/leaderboard'
    | '/$organizationId/people'
    | '/$organizationId/'
    | '/$organizationId/matches/$matchId'
    | '/$organizationId/matches/new'
    | '/$organizationId/matches/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$organizationId/leaderboard'
    | '/$organizationId/people'
    | '/$organizationId'
    | '/$organizationId/matches/$matchId'
    | '/$organizationId/matches/new'
    | '/$organizationId/matches'
  id:
    | '__root__'
    | '/'
    | '/$organizationId'
    | '/$organizationId/leaderboard'
    | '/$organizationId/people'
    | '/$organizationId/'
    | '/$organizationId/matches/$matchId'
    | '/$organizationId/matches/new'
    | '/$organizationId/matches/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrganizationIdRouteRoute: typeof OrganizationIdRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$organizationId': {
      id: '/$organizationId'
      path: '/$organizationId'
      fullPath: '/$organizationId'
      preLoaderRoute: typeof OrganizationIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$organizationId/': {
      id: '/$organizationId/'
      path: '/'
      fullPath: '/$organizationId/'
      preLoaderRoute: typeof OrganizationIdIndexRouteImport
      parentRoute: typeof OrganizationIdRouteRoute
    }
    '/$organizationId/leaderboard': {
      id: '/$organizationId/leaderboard'
      path: '/leaderboard'
      fullPath: '/$organizationId/leaderboard'
      preLoaderRoute: typeof OrganizationIdLeaderboardRouteImport
      parentRoute: typeof OrganizationIdRouteRoute
    }
    '/$organizationId/people': {
      id: '/$organizationId/people'
      path: '/people'
      fullPath: '/$organizationId/people'
      preLoaderRoute: typeof OrganizationIdPeopleRouteImport
      parentRoute: typeof OrganizationIdRouteRoute
    }
    '/$organizationId/matches/': {
      id: '/$organizationId/matches/'
      path: '/matches'
      fullPath: '/$organizationId/matches/'
      preLoaderRoute: typeof OrganizationIdMatchesIndexRouteImport
      parentRoute: typeof OrganizationIdRouteRoute
    }
    '/$organizationId/matches/$matchId': {
      id: '/$organizationId/matches/$matchId'
      path: '/matches/$matchId'
      fullPath: '/$organizationId/matches/$matchId'
      preLoaderRoute: typeof OrganizationIdMatchesMatchIdRouteImport
      parentRoute: typeof OrganizationIdRouteRoute
    }
    '/$organizationId/matches/new': {
      id: '/$organizationId/matches/new'
      path: '/matches/new'
      fullPath: '/$organizationId/matches/new'
      preLoaderRoute: typeof OrganizationIdMatchesNewRouteImport
      parentRoute: typeof OrganizationIdRouteRoute
    }
  }
}

interface OrganizationIdRouteRouteChildren {
  OrganizationIdLeaderboardRoute: typeof OrganizationIdLeaderboardRoute
  OrganizationIdPeopleRoute: typeof OrganizationIdPeopleRoute
  OrganizationIdIndexRoute: typeof OrganizationIdIndexRoute
  OrganizationIdMatchesMatchIdRoute: typeof OrganizationIdMatchesMatchIdRoute
  OrganizationIdMatchesNewRoute: typeof OrganizationIdMatchesNewRoute
  OrganizationIdMatchesIndexRoute: typeof OrganizationIdMatchesIndexRoute
}

const OrganizationIdRouteRouteChildren: OrganizationIdRouteRouteChildren = {
  OrganizationIdLeaderboardRoute: OrganizationIdLeaderboardRoute,
  OrganizationIdPeopleRoute: OrganizationIdPeopleRoute,
  OrganizationIdIndexRoute: OrganizationIdIndexRoute,
  OrganizationIdMatchesMatchIdRoute: OrganizationIdMatchesMatchIdRoute,
  OrganizationIdMatchesNewRoute: OrganizationIdMatchesNewRoute,
  OrganizationIdMatchesIndexRoute: OrganizationIdMatchesIndexRoute,
}

const OrganizationIdRouteRouteWithChildren =
  OrganizationIdRouteRoute._addFileChildren(OrganizationIdRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrganizationIdRouteRoute: OrganizationIdRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
